name: wide_clean
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.1.5
  equatable: ^2.0.5
  get_it: ^7.7.0
  flutter_lints: ^4.0.0
  intl: ^0.19.0
  floor: ^1.5.0
  retrofit: ^4.1.0
  flutter_hooks: ^0.20.5
  dio: ^5.4.3+1

  build: ^2.4.1
  json_annotation: ^4.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  retrofit_generator: ^8.1.0
  json_serializable: ^6.0.1
  build_runner: ^2.4.10

flutter:
  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Geometria
      fonts:
        - asset: assets/fonts/geometria/Geometria-Bold.ttf
          weight: 600
        - asset: assets/fonts/geometria/Geometria.ttf
          weight: 500

  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
