name: wide_clean
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.1.5
  equatable: ^2.0.5
  get_it: ^7.7.0
  flutter_lints: ^4.0.0
  intl: ^0.19.0
  floor: ^1.5.0
  retrofit: ^4.1.0
  flutter_hooks: ^0.20.5
  dio: ^5.4.3+1
  pretty_dio_logger: ^1.3.1

  build: ^2.4.1
  json_annotation: ^4.3.0
  flutter_svg: 2.0.9
  bloc: ^8.1.4
  vibration: ^1.9.0
  video_player: ^2.8.6
  expandable_text: ^2.3.0
  shimmer: ^3.0.0
  image_picker: ^1.1.2
  provider: ^6.1.2
  mask_text_input_formatter: ^2.9.0
  path: ^1.9.0
  path_provider: ^2.1.3
  image_gallery_saver: ^2.0.3
  gallery_saver: ^2.3.2
  url_launcher: ^6.2.6
  flutter_xlider: ^3.5.0
  assets_audio_player: ^3.1.1
  syncfusion_flutter_sliders: ^25.2.6
  image: ^4.2.0
  permission_handler: ^11.3.1
  camera: ^0.11.0+1
  photo_manager: ^3.1.1
  flutter_staggered_grid_view: ^0.7.0
  chewie: ^1.8.1
  video_thumbnail: ^0.5.3
  pinput: ^5.0.0
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  retrofit_generator: ^8.1.0
  json_serializable: ^6.0.1
  build_runner: ^2.4.10

flutter:
  uses-material-design: true

  assets:
    - assets/images/home/
    - assets/icons/home/
    - assets/icons/login/
    - assets/icons/nav_bar/left_side/
    - assets/icons/nav_bar/right_side/
    - assets/icons/profile/
    - assets/icons/recommendation/
    - assets/icons/sign_up/
    - assets/icons/splash/logo.svg
    - assets/images/recommandation/
    - assets/images/home/avatar.png
    - assets/icons/profile/person_icon.svg


  fonts:
    - family: Geometria
      fonts:
        - asset: assets/fonts/Geometria.ttf
  

  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #

